### ISSUE TITLE
Unable to start - npm start fails

### ISSUE THREAD

**Issue by mirchiseth** [andrew-codes/community-board#48]
Here is the log I get on command line

community-board pkn$ npm start

> codenamed-pancakes@0.0.0 start /Users/pkn/tmp/cloudspace/community-board
> gulp

[00:49:16] Using gulpfile ~/tmp/cloudspace/community-board/gulpfile.js
[00:49:16] Starting 'webpack'...
[00:49:16] Starting 'start-server'...
[00:49:16] Finished 'start-server' after 1.45 ms
[00:49:16] [webpack-dev-server] http://localhost:8888/assets/bundle.js
[00:49:16] Finished 'webpack' after 92 ms
[00:49:16] Starting 'default'...
[00:49:16] Finished 'default' after 3.97 μs
[00:49:16] [nodemon] v1.4.1
[00:49:16] [nodemon] to restart at any time, enter `rs`
[00:49:16] [nodemon] watching: _._
[00:49:16] [nodemon] starting `node --harmony /Users/pkn/tmp/cloudspace/community-board/src/index.js`
/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/lib/babel/transformation/file/index.js:628
      throw err;
            ^
TypeError: /Users/pkn/tmp/cloudspace/community-board/src/server/routes/AuthorizationCallback.js: Cannot read property 'declareTemporary' of null
    at getOuterFnExpr (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/lib/visit.js:283:35)
    at Context.types.PathVisitor.fromMethodsObject.visitFunction (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/lib/visit.js:106:23)
    at Context.invokeVisitorMethod (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:310:43)
    at Visitor.PVp.visitWithoutReset (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:184:28)
    at visitChildren (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:230:21)
    at Visitor.PVp.visitWithoutReset (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:192:16)
    at Visitor.PVp.visit (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:124:25)
    at Function.transform (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/node_modules/regenerator/lib/visit.js:29:11)
    at NodePath.exit (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/lib/babel/transformation/transformers/other/regenerator.js:34:32)
    at NodePath.call (/Users/pkn/tmp/cloudspace/community-board/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
[00:49:17] [nodemon] app crashed - waiting for file changes before starting...

**Comment by mirchiseth** [comment]
Changing babel versions to 5.8.20 fixes this.
